version: '3.1'

services:

  orchestrator:
    build:
      context: ./orchestrator/
    container_name: orchestrator
    ports:
      - 8080:8080

  jwt-authorization-server:
    build:
      context: ./jwt-authorization-server
    container_name: jwt-authorization-server
    ports:
      - 9999:9999